services:
  - type: web
    name: scraven-api
    runtime: docker
    plan: free
    region: oregon
    branch: main
    rootDir: .
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: APIFY_API_KEY
        sync: false
      - key: APIFY_TOKEN
        sync: false
      - key: GMAIL_USER
        sync: false
      - key: GMAIL_APP_PASS
        sync: false
      - key: TELEGRAM_TOKEN
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
    autoDeploy: true